### ISSUE TITLE
confint method for `geeglm` objects not working well

### ISSUE THREAD

**Issue by iago-pssjd** [tidymodels/broom#714] opened 2019-06-13 13:17 UTC
I tried to use the method [confint.geeglm](https://www.rdocumentation.org/packages/broom/versions/0.4.5/topics/confint.geeglm), but I got the following:

```
# creating a dataframe
set.seed(123)
library(geepack)
data(state)
ds <- data.frame(state.region, state.x77)

# model
geefit <-
  geepack::geeglm(
    formula = Income ~ Frost + Murder,
    id = state.region,
    data = ds,
    family = gaussian,
    corstr = "exchangeable"
  )

# confint.geeglm method
confint(geefit)
#> Waiting for profiling to be done...
#> Error in `[.data.frame`(summ$coefficients, , "Std. Error", drop = FALSE) : 
#>   undefined columns selected

# But it works if it is specified
broom:::confint.geeglm(geefit)
#>                  lwr      upr
#> (Intercept) 3607.596 5204.790
#> Frost         -2.723    6.097
#> Murder       -84.167   38.838
```

**Comment by IndrajeetPatil** [comment] 2019-06-13 19:26
I can't reproduce this error. Are you by any chance using the `CRAN` version of `broom`? I'd recommend updating to the development version on `GitHub` which has taken care of a lot of known issues with some of the tidiers.

``` r
# creating a dataframe
set.seed(123)
library(geepack)
data(state)
ds <- data.frame(state.region, state.x77)

# model
geefit <-
  geepack::geeglm(
    formula = Income ~ Frost + Murder,
    id = state.region,
    data = ds,
    family = gaussian,
    corstr = "exchangeable"
  )

# tidy output with confidence intervals
broom::tidy(x = geefit, conf.int = TRUE)
#> # A tibble: 3 x 7
#>   term        estimate std.error statistic p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 (Intercept)  4406.      407.     117.      0      3608.     5205.  
#> 2 Frost           1.69      2.25     0.562   0.453    -2.72      6.10
#> 3 Murder        -22.7      31.4      0.522   0.470   -84.2      38.8

# with the helper function
broom::confint_tidy(geefit)
#> # A tibble: 3 x 2
#>   conf.low conf.high
#>      <dbl>     <dbl>
#> 1  3608.     5205.  
#> 2    -2.72      6.10
#> 3   -84.2      38.8
```

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                                    
#>  version  R version 3.6.0 alpha (2019-03-29 r76300)
#>  os       Windows 10 x64                           
#>  system   x86_64, mingw32                          
#>  ui       RTerm                                    
#>  language (EN)                                     
#>  collate  English_United States.1252               
#>  ctype    English_United States.1252               
#>  tz       America/New_York                         
#>  date     2019-06-13                               
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source                         
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                 
#>  backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)                 
#>  broom         0.5.2.9001 2019-05-29 [1] local                          
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                 
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                 
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                 
#>  desc          1.2.0      2019-04-03 [1] Github (r-lib/desc@c860e7b)    
#>  devtools      2.0.2      2019-04-08 [1] CRAN (R 3.6.0)                 
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                 
#>  dplyr         0.8.1      2019-05-14 [1] CRAN (R 3.6.0)                 
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                 
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c) 
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                 
#>  geepack     * 1.2-1      2016-09-24 [1] CRAN (R 3.5.0)                 
#>  generics      0.0.2      2019-03-05 [1] Github (r-lib/generics@c15ac43)
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                 
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                 
#>  knitr         1.23       2019-05-18 [1] CRAN (R 3.6.0)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                 
#>  pillar        1.4.1      2019-05-28 [1] CRAN (R 3.6.0)                 
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.0)                 
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                 
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                 
#>  purrr         0.3.2      2019-03-15 [1] CRAN (R 3.6.0)                 
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                 
#>  Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.6.0)                 
#>  remotes       2.0.4      2019-04-10 [1] CRAN (R 3.6.0)                 
#>  rlang         0.3.4      2019-04-07 [1] CRAN (R 3.6.0)                 
#>  rmarkdown     1.13       2019-05-22 [1] CRAN (R 3.6.0)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                 
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                 
#>  testthat      2.1.1      2019-04-23 [1] CRAN (R 3.6.0)                 
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                 
#>  tidyr         0.8.3      2019-03-01 [1] CRAN (R 3.6.0)                 
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                 
#>  usethis       1.5.0.9000 2019-06-05 [1] Github (r-lib/usethis@2baa06f) 
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                 
#>  vctrs         0.1.0      2018-11-29 [1] CRAN (R 3.6.0)                 
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                 
#>  xfun          0.7        2019-05-14 [1] CRAN (R 3.6.0)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                 
#>  zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.5.1)                 
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0alpha/library
```

</details>

**Comment by iago-pssjd** [comment] 2019-06-14 08:40
Thanks by the answer. I installed the development version of `broom` on `Github`, and `broom::tidy(x = geefit, conf.int = TRUE)` and `broom::confint_tidy(geefit)` work me well as to you, but I continue having the issue that I described above, that is:
``` r
# creating a dataframe
set.seed(123)
library(geepack)
data(state)
ds <- data.frame(state.region, state.x77)

# model
geefit <-
  geepack::geeglm(
    formula = Income ~ Frost + Murder,
    id = state.region,
    data = ds,
    family = gaussian,
    corstr = "exchangeable"
  )

# confint.geeglm method
confint(geefit)
#> Waiting for profiling to be done...
#> Error in `[.data.frame`(summ$coefficients, , "Std. Error", drop = FALSE): undefined columns selected
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>
<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Spanish_Spain.1252          
#>  ctype    Spanish_Spain.1252          
#>  tz       Europe/Paris                
#>  date     2019-06-14                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.2)
#>  backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.2)
#>  callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
#>  cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.2)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.2)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
#>  evaluate      0.12    2018-10-09 [1] CRAN (R 3.5.2)
#>  fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.2)
#>  glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.2)
#>  highr         0.7     2018-06-09 [1] CRAN (R 3.5.2)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.2)
#>  knitr         1.21    2018-12-10 [1] CRAN (R 3.5.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.2)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.2)
#>  processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.2)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
#>  R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.2)
#>  remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.2)
#>  rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)
#>  rmarkdown     1.11    2018-12-08 [1] CRAN (R 3.5.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.2.4   2018-07-20 [1] CRAN (R 3.5.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.2)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.2)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
#>  xfun          0.4     2018-10-23 [1] CRAN (R 3.5.2)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)
#> 
#> [1] C:/Program Files/R/R-3.5.2/library
```
</details>

**Comment by IndrajeetPatil** [comment] 2019-06-14 12:49
You are using `stats::confint` now, while your original question was about `broom::confint_tidy`.

This error has nothing to do with the `broom` package, but to do with `stats` package. This is also apparent in the traceback for this error:
```r
> traceback()
7: stop("undefined columns selected")
6: `[.data.frame`(summ$coefficients, , "Std. Error", drop = FALSE)
5: summ$coefficients[, "Std. Error", drop = FALSE]
4: profile.glm(object, which = parm, alpha = (1 - level)/4, trace = trace)
3: profile(object, which = parm, alpha = (1 - level)/4, trace = trace)
2: confint.glm(geefit)
1: stats::confint(geefit)
```

**Comment by iago-pssjd** [comment] 2019-06-14 13:04
Now I understand the problem:
```
> class(geefit) 
[1] "geeglm" "gee"    "glm"    "lm"
```
Thus, the first method which `confint` tries is `glm` instead of which should be the correct in this case, `geeglm`.
Thank you!

**Comment by IndrajeetPatil** [comment] 2019-06-14 15:17
Good to know. 

If your question has been satisfactorily answered, please close this issue. Thanks.

**Comment by iago-pssjd** [comment] 2019-06-14 17:51
Maybe the question now is if it is necessary to include `gee`,`glm` and `lm` as classes of `geefit`, or why are them included, since otherwise `confint(geefit)` just would look for the method `confint.geeglm` of `confint`. Maybe have I to open a new issue for these question?

Once this question become clear, I could ask to the R-developers mailing list if it would be possible that S3 methods check different classes of the object evaluated (like `geeglm`) when the previous ones (like `glm` produce errors) or if it could be another solution to this issue.

**Comment by IndrajeetPatil** [comment] 2019-06-14 17:58
But that issue is relevant for `geepack` maintainers or `R-core`, not sure what `broom` can do about it (`confint` is *not* part of `broom` [functions](https://broom.tidyverse.org/reference/index.html)).

**Comment by iago-pssjd** [comment] 2019-06-14 18:00
You are right, I was confused.
And thank you!

**Comment by iago-pssjd** [comment] 2019-06-14 18:00
You are right, I was confused.
And thank you!

**Comment by iago-pssjd** [comment] 2019-06-18 15:56
Finally, it seems that the problem is with `broom` package, since it doesn't export the `confint.geeglm` method.

**Comment by alexpghayes** [comment] 2019-08-07 15:59
Hey! I know that it's frustrating that `geepack` doesn't have a `confint.geeglm()` method, but really the best place to add that method would be in `geepack` itself. I would email the maintainers of `geepack` and see what they have to say! `broom` will sometimes create internal tools like `confint.geeglm()` to facilitate tidy methods, but the general philosophy is to avoid exporting these.

**Closed by alexpghayes** 2019-08-07 15:59 UTC
