### ISSUE TITLE
`conf.int` not working for `gam` objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#564] opened 2018-12-24 17:34 UTC
``` r
# setup
set.seed(123)
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-26. For overview type 'help("mgcv-package")'.

# model
mod <- mgcv::gam(formula = mpg ~ s(hp) + am + qsec,
                 data = mtcars)

# checking summary
summary(mod)
#> 
#> Family: gaussian 
#> Link function: identity 
#> 
#> Formula:
#> mpg ~ s(hp) + am + qsec
#> 
#> Parametric coefficients:
#>             Estimate Std. Error t value Pr(>|t|)   
#> (Intercept)  16.7017     9.8259   1.700  0.10083   
#> am            4.3704     1.5554   2.810  0.00918 **
#> qsec          0.0904     0.5253   0.172  0.86468   
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Approximate significance of smooth terms:
#>         edf Ref.df     F p-value   
#> s(hp) 2.364  3.024 6.337 0.00207 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> R-sq.(adj) =  0.797   Deviance explained = 82.6%
#> GCV = 8.8375  Scale est. = 7.3562    n = 32

# checking confidence intervals
confint.default(mod)
#>                   2.5 %    97.5 %
#> (Intercept)  -2.5566531 35.960031
#> am            1.3217264  7.418968
#> qsec         -0.9392590  1.120054
#> s(hp).1      -3.7979805  1.305361
#> s(hp).2      -4.3718602  2.368082
#> s(hp).3      -0.7354714  0.693483
#> s(hp).4      -3.1085305  1.643785
#> s(hp).5      -0.7277549  1.588892
#> s(hp).6      -1.3045211  2.966570
#> s(hp).7      -0.8450272  1.888936
#> s(hp).8     -12.1520816  3.882422
#> s(hp).9      -7.8065475 -1.065430

# tidier output
broom::tidy(x = mod,
            parametric = TRUE,
            conf.int = TRUE)
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  16.7        9.83      1.70  0.101  
#> 2 am            4.37       1.56      2.81  0.00918
#> 3 qsec          0.0904     0.525     0.172 0.865
```

<sup>Created on 2018-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by alexpghayes** [comment] 2018-12-29 01:07
`tidy.gam()` doesn't support a `conf.int` argument, so this is just getting eaten silently in the `...`. This is another case of #413. Let me ask about the status of `ellipsis` and if it's headed to CRAN so I can use it in the next release.

**Comment by IndrajeetPatil** [comment] 2018-12-29 03:14
Sorry, I wasn't clear. I meant to say that the confidence intervals for estimates are available for `gam` models, but they are not currently included in tidier output. This should be a beginner-friendly commit.

**Comment by llendway** [comment] 2019-01-19 15:45
I'm going to try this one. I just want to confirm with @alexpghayes that the issue is that there should be variables called conf.low and conf.high in the tidy output when conf.int = TRUE when the gam function is used, similar to when lm is used.

**Comment by llendway** [comment] 2019-01-19 15:49
Here's an example of output from lm. I assume we want the output from gam to look like this, too:
``` r
mod_lm <- lm(formula = mpg ~ hp + am + qsec,
             data = mtcars)

broom::tidy(x = mod_lm,
            parametric = TRUE,
            conf.int = TRUE)
#> # A tibble: 4 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)  16.6      11.2        1.49  0.148     -6.25     39.5   
#> 2 hp           -0.0491    0.0134    -3.66  0.00104   -0.0766   -0.0216
#> 3 am            5.98      1.34       4.47  0.000117   3.24      8.72  
#> 4 qsec          0.461     0.513      0.899 0.377     -0.590     1.51
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gavinsimpson** [comment] 2019-01-21 22:42
It'd be handy if we can have standard errors that aren't conditional on the estimated smoothness parameter(s). It complicates the implementation however but everything we need is given by `vcov(model, unconditional = TRUE)` (and we may want to pass `unconditional` through so need that as an argument.)

**Comment by alexpghayes** [comment] 2019-01-22 17:46
Yeah, let's make `unconditional` an argument.

**Comment by alexpghayes** [comment] 2019-03-03 21:09
Closing in favor of #615

**Closed by alexpghayes** 2019-03-03 21:09 UTC
Labels: beginner-friendly, feature-request, tidy-dev-day :nerd_face:
