### ISSUE TITLE
glance on an aov model reports the wrong df value

### ISSUE THREAD

**Issue by cmartin** [tidymodels/broom#212] opened 2017-03-16 02:37 UTC
Unless I'm misunderstanding something, glance should report the same df as in summary (e.g. 2 in this example) but it seems to always report df+1

```{r}
library(broom)

d <- data.frame(
  y = c(3,4,3.5,4.1,6,7),
  group = c("a","b","a","b","c","c")
)
m <- aov(y~group,data = d)

summary(m)
glance(m)
```

This is with broom 0.4.2 (the current version with tidyverse if I'm not mistaken)

**Comment by kcmacstat** [comment] 2017-06-28 04:16
Same problem occurs with glance on an lm model, i.e., glance(lm.object). The df is computed incorrectly even though summary(lm.object) shows the correct df.

**Comment by lemna** [comment] 2017-11-13 14:14
`glance()` should probably return the numerator and denumerator df for the F statistic. It doesn't do that because it uses the `df` slot from `summary.lm()` (which contains the rank of the model matrix). It might be more sensible to use the df from the `fstatistic` slot.

**Comment by alexpghayes** [comment] 2019-03-05 05:11
In #624 I've moved to the numerator degrees of freedom for the F-statistic for `lm` objects. Here, I'm a little less certain about what to do. In a particular ANOVA table there are potentially many F-tests of interest, all with different degrees of freedom. So far the approach has been to treat the `aov` like the corresponding regression, and report the statistics for the regression, but I'm not sure how I feel about this. I almost think `glance.aov()` should be an error instead. Thoughts @dgrtwo?

**Comment by alexpghayes** [comment] 2019-03-05 05:31
Tentatively I've thrown an error.

**Comment by simonpcouch** [comment] 2020-08-15 21:05
Addressed in 0.7.0. :-)

**Closed by simonpcouch** 2020-08-15 21:05 UTC
Labels: consistency/specification
