### ISSUE TITLE
Feature request: tidy() for rma objects (metafor package)

### ISSUE THREAD

**Issue by thoughtsnippet** [tidymodels/broom#204] opened 2017-03-02 11:14 UTC

**Comment by talgalili** [comment] 2017-03-02 12:46
It is available in this fork:
https://github.com/talgalili/broom/commit/a4f243d346a5d888d7d6b569e8f105befaa95123
Specifically, here is the R code:
https://github.com/talgalili/broom/blob/master/R/metafor_tidiers.R

I hope David would get to add it.

Cheers,
Tal

**Comment by alexpghayes** [comment] 2018-06-06 18:40
Would love to add these. Can you make a PR?

**Comment by IndrajeetPatil** [comment] 2019-03-10 20:12
Duplicate of #621

**Closed** 2019-03-10 20:13 UTC
Labels: new-tidiers
