### ISSUE TITLE
glance() on tbl_df throws "infinite recursion" error

### ISSUE THREAD

**Issue by holgerbrandl** [tidymodels/broom#154] opened 2016-08-19 12:59 UTC
Using the current version from github (as well as with the v0.4.1 release) the following code fails

```
require(broom)
require(dplyr)
glance(tbl_df(iris ))
```

The error is

```
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.utf8        LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0      broom_0.4.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6     lattice_0.20-33 tidyr_0.6.0     psych_1.6.6    
 [5] assertthat_0.1  grid_3.3.1      R6_2.1.2        plyr_1.8.4     
 [9] nlme_3.1-128    DBI_0.5         magrittr_1.5    stringi_1.1.1  
[13] reshape2_1.4.1  tools_3.3.1     stringr_1.0.0   parallel_3.3.1 
[17] mnormt_1.5-4    tibble_1.1    
```

**Comment by nabilabd** [comment] 2016-08-26 15:38
I think the issue is in the `wrap_tbl_df` function (in rowwise_df_tidiers.R).It seems that when `glance` is called on a `tbl_df` which isn't a rowwise_df, then `glance` is just getting called again on it. 

So if you have, 
```
iris <- tbl_df(iris)
```
then `glance(iris)` should have output basically the same as `glance(as.data.frame(iris))`. From the comments on that part, it seems like that code usually works, but I'm not sure when the code currently there would be failing or working, though.

**Comment by alexpghayes** [comment] 2018-06-06 20:01
@dgrtwo My inclination is just to deprecate the `rowwise` tidiers. Thoughts? Could be painful for people still using `do` workflows.

**Comment by dgrtwo** [comment] 2018-06-07 19:40
We should definitely deprecate the rowwise tidiers.

For 0.5.0, we should:

* Add a warning rather than hard deprecating (since some people are probably using them)
* Make sure all augment methods have data, and set data = NULL as default (rather than using missing() or default arguments)

**Comment by alexpghayes** [comment] 2018-06-07 22:16
Given that we're deprecating all the data frame tidiers (rowwise too now), I'm going to close this.

**Comment by mine-cetinkaya-rundel** [comment] 2018-09-24 16:30
I don't know how long you plan on keeping the deprecated message for `glance.data.frame()` but it would be nice to give a similarly informative message when one accidentally tries to `glance()` at a `tbl_df`. The current error is not informative.

Alternatively the help for `glance()` could mention that `x` cannot be a data frame or tibble.

Personally I confuse the verbs `tibble::glimpse()` and `broom::glance()` regularly, and I suspect a few others might as well, so an informative error message would be helpful.

The following is a faux-reprex as the code crashes `reprex::reprex()`:

```r
> library(tidyverse)
> library(broom)
> class(mtcars)
[1] "data.frame"
> glance(mtcars)
# A tibble: 1 x 4
   nrow  ncol complete.obs na.fraction
  <int> <int>        <int>       <dbl>
1    32    11           32           0
Warning message:
'glance.data.frame' is deprecated.
See help("Deprecated") 
> class(starwars)
[1] "tbl_df"     "tbl"        "data.frame"
> glance(starwars)
Error: C stack usage  7970160 is too close to the limit
```

**Comment by alexpghayes** [comment] 2018-09-24 16:49
The 0.7.0 release is likely a while out, but we'll be doing a hard deprecation of all data frame tidiers then. Perhaps:

```r
glance(some_data_frame_like_object)
#> Error: There is no glance method for data frames. Did you mean to use `dplyr::glimpse()`?
```

**Comment by mine-cetinkaya-rundel** [comment] 2018-09-24 16:52
Something like that might be helpful, and one that would work on both `data.frame` and `tbl_df`. Thanks!

**Comment by alexpghayes** [comment] 2018-10-01 20:14
There's now an informative error in development version of `broom`:

``` r
library(broom)

glance(iris)
#> Error: There is no glance method for data frames. Did you mean `dplyr::glimpse()`?
glance(tibble::as_tibble(iris))
#> Error: There is no glance method for tibbles. Did you mean `dplyr::glimpse()`?
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mine-cetinkaya-rundel** [comment] 2018-10-01 23:59
Great, thanks!

It's `tibble::glimpse()` right, not `dplyr::glimpse()`?

**Comment by alexpghayes** [comment] 2019-03-03 20:31
Yes! Need to update the error message.

**Closed** 2019-03-03 20:32 UTC
Labels: bug, wontfix
