### ISSUE TITLE
Check that metafor::rma() tidiers play well with the mice package

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#689] opened 2019-04-11 02:41 UTC
See my exact concerns below. 

This is just setup for the example.
``` r
# setup
set.seed(123)
library(broom)
library(metafor)
#> Loading required package: Matrix
#> Loading 'metafor' package (version 2.0-0). For an overview 
#> and introduction to the package please type: help(metafor).

# let's create a dataframe with different effect sizes
(df_results <-
  structure(
    .Data = list(estimate = c(
      0.382047603321706, 0.780783111514665,
      0.425607573765058, 0.558365541235078, 0.956473848429961
    ), std.error = c(
      0.0465576338644502,
      0.0330218199731529, 0.0362834986178494, 0.0480571500648261, 0.062215818388157
    ), t.value = c(
      8.20590677855356, 23.6444603038067, 11.7300588415607,
      11.6187818146078, 15.3734833553524
    ), conf.low = c(
      0.290515146096969,
      0.715841986960399, 0.354354575031406, 0.46379116008131, 0.827446138277154
    ), conf.high = c(
      0.473580060546444, 0.845724236068931, 0.496860572498711,
      0.652939922388847, 1.08550155858277
    ), p.value = c(
      3.28679518728519e-15,
      4.04778497135963e-75, 7.59757330804449e-29, 5.45155840151592e-26,
      2.99171217913312e-13
    ), df.residual = c(
      394L, 358L, 622L, 298L,
      22L
    )),
    row.names = c(NA, -5L),
    class = c("tbl_df", "tbl", "data.frame")
  ))
#> # A tibble: 5 x 7
#>   estimate std.error t.value conf.low conf.high  p.value df.residual
#>      <dbl>     <dbl>   <dbl>    <dbl>     <dbl>    <dbl>       <int>
#> 1    0.382    0.0466    8.21    0.291     0.474 3.29e-15         394
#> 2    0.781    0.0330   23.6     0.716     0.846 4.05e-75         358
#> 3    0.426    0.0363   11.7     0.354     0.497 7.60e-29         622
#> 4    0.558    0.0481   11.6     0.464     0.653 5.45e-26         298
#> 5    0.956    0.0622   15.4     0.827     1.09  2.99e-13          22

# object from meta-analysis
meta_res <- metafor::rma(
  yi = estimate,
  sei = std.error,
  measure = "GEN",
  intercept = TRUE,
  data = df_results,
  vtype = "LS",
  method = "REML",
  weighted = TRUE,
  test = "z",
  level = 95,
  digits = 4
)

# summary from metafor
summary(meta_res)
#> 
#> Random-Effects Model (k = 5; tau^2 estimator: REML)
#> 
#>   logLik  deviance       AIC       BIC      AICc  
#>  -0.0069    0.0138    4.0138    2.7864   16.0138  
#> 
#> tau^2 (estimated amount of total heterogeneity): 0.0561 (SE = 0.0411)
#> tau (square root of estimated tau^2 value):      0.2368
#> I^2 (total heterogeneity / total variability):   96.81%
#> H^2 (total variability / sampling variability):  31.31
#> 
#> Test for Heterogeneity: 
#> Q(df = 4) = 108.5509, p-val < .0001
#> 
#> Model Results:
#> 
#> estimate      se    zval    pval   ci.lb   ci.ub     
#>   0.6188  0.1079  5.7362  <.0001  0.4074  0.8302  ***
#> 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

# tidy output

A couple of concerns here-
1. Most of the `broom` tidiers return column `term`, but here there are two columns `study` and `type`. Why not have just one column called `term` with entries like `"study 1"`, `"study 2"`, ..., `"overall summary"`?
2. The `tidy` dataframe leaves out `z.value` column (which will contain `zval`). As was mentioned somewhere else, `broom` tidiers are not expected to be opinionated about what should be returned, so it will be nice if this tidier also returns _z_-value.

```r
broom::tidy(meta_res)
#> # A tibble: 6 x 6
#>   study   type    estimate std.error statistic  p.value
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>    <dbl>
#> 1 1       study      0.382    0.0466      8.21 NA      
#> 2 2       study      0.781    0.0330     23.6  NA      
#> 3 3       study      0.426    0.0363     11.7  NA      
#> 4 4       study      0.558    0.0481     11.6  NA      
#> 5 5       study      0.956    0.0622     15.4  NA      
#> 6 overall summary    0.619    0.108       5.74  9.68e-9
```

# model summary

Most of the `S3 glance` methods in `broom` return measures of quality of models, like `logLik`,  `deviance`, `AIC`, `BIC`, `AICc`. All of these measures are available in `summary` object from `metafor` but is not returned by `glance`. To be consistent with the rest of the tidiers, I think `glance` here should return all these measures.

```r
broom::glance(meta_res)
#> # A tibble: 1 x 11
#>    nobs measure method i.squared h.squared tau.squared tau.squared.se
#>   <int> <chr>   <chr>      <dbl>     <dbl>       <dbl>          <dbl>
#> 1     5 GEN     REML        96.8      31.3      0.0561         0.0411
#> # ... with 4 more variables: cochran.qe <dbl>, p.value.cochran.qe <dbl>,
#> #   cochran.qm <dbl>, p.value.cochran.qm <dbl>
```

<sup>Created on 2019-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                                    
#>  version  R version 3.6.0 alpha (2019-03-29 r76300)
#>  os       Windows 10 x64                           
#>  system   x86_64, mingw32                          
#>  ui       RTerm                                    
#>  language (EN)                                     
#>  collate  English_United States.1252               
#>  ctype    English_United States.1252               
#>  tz       America/New_York                         
#>  date     2019-04-10                               
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib
#>  assertthat    0.2.1      2019-03-21 [1]
#>  backports     1.1.4      2019-04-10 [1]
#>  broom       * 0.5.2.9001 2019-04-09 [1]
#>  callr         3.2.0      2019-03-15 [1]
#>  cli           1.1.0      2019-03-19 [1]
#>  crayon        1.3.4      2017-09-16 [1]
#>  desc          1.2.0      2019-04-03 [1]
#>  devtools      2.0.2      2019-04-08 [1]
#>  digest        0.6.18     2018-10-10 [1]
#>  dplyr         0.8.0.9009 2019-03-15 [1]
#>  evaluate      0.13       2019-02-12 [1]
#>  fansi         0.4.0      2018-11-05 [1]
#>  fs            1.2.7      2019-03-19 [1]
#>  generics      0.0.2      2019-03-05 [1]
#>  glue          1.3.1      2019-03-12 [1]
#>  highr         0.8        2019-03-20 [1]
#>  htmltools     0.3.6      2017-04-28 [1]
#>  knitr         1.22.8     2019-04-08 [1]
#>  lattice       0.20-38    2018-11-04 [2]
#>  magrittr      1.5        2014-11-22 [1]
#>  Matrix      * 1.2-17     2019-03-22 [1]
#>  memoise       1.1.0      2017-04-21 [1]
#>  metafor     * 2.0-0      2017-06-22 [1]
#>  nlme          3.1-137    2018-04-07 [2]
#>  pillar        1.3.1      2018-12-15 [1]
#>  pkgbuild      1.0.3      2019-03-20 [1]
#>  pkgconfig     2.0.2      2018-08-16 [1]
#>  pkgload       1.0.2      2018-10-29 [1]
#>  prettyunits   1.0.2      2015-07-13 [1]
#>  processx      3.3.0      2019-03-10 [1]
#>  ps            1.3.0      2018-12-21 [1]
#>  purrr         0.3.2      2019-03-15 [1]
#>  R6            2.4.0      2019-02-14 [1]
#>  Rcpp          1.0.1      2019-03-17 [1]
#>  remotes       2.0.4      2019-04-10 [1]
#>  rlang         0.3.4      2019-04-07 [1]
#>  rmarkdown     1.12.3     2019-03-25 [1]
#>  rprojroot     1.3-2      2018-01-03 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.4.3      2019-03-12 [1]
#>  stringr       1.4.0      2019-02-10 [1]
#>  testthat      2.0.1      2018-10-13 [1]
#>  tibble        2.1.1      2019-03-16 [1]
#>  tidyr         0.8.3.9000 2019-03-07 [1]
#>  tidyselect    0.2.5      2018-10-11 [1]
#>  usethis       1.5.0      2019-04-07 [1]
#>  utf8          1.1.4      2018-05-24 [1]
#>  vctrs         0.1.0.9002 2019-03-07 [1]
#>  withr         2.1.2      2018-03-15 [1]
#>  xfun          0.6        2019-04-02 [1]
#>  yaml          2.2.0      2018-07-25 [1]
#>  zeallot       0.1.0      2018-01-28 [1]
#>  source                            
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  local                             
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/desc@c860e7b)       
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  Github (tidyverse/dplyr@df735d1)  
#>  CRAN (R 3.6.0)                    
#>  Github (brodieG/fansi@ab11e9c)    
#>  CRAN (R 3.6.0)                    
#>  Github (r-lib/generics@c15ac43)   
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  Github (yihui/knitr@6103edd)      
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.3)                    
#>  Github (rstudio/rmarkdown@503cc5f)
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  Github (tidyverse/tidyr@7a51bfd)  
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/vctrs@6b8c98a)      
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.6.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0alpha/library
```

</details>

**Comment by alexpghayes** [comment] 2019-04-11 02:58
cc @malcolmbarrett @cantabile any thoughts?

**Comment by malcolmbarrett** [comment] 2019-04-11 03:54
1) I considered that, too. `term` really seemed like it was trying to cram the results into the broom mold. I felt like the informativeness of `study` and `type` made more sense because they aren't the names of variables, as in regression. Whatever is decided should be used in any future tidiers for meta-analyses for sure, though.

2) that's a bug! It should, and I know why it's not. I'll fix it.

**Comment by alexpghayes** [comment] 2019-04-11 03:58
1. I like `study` as well.
2. On board to include z-statistic.

3. For `glance()`: can we move `nobs` to the far right? This is more consistent with the rest of broom. Technically the rest of broom uses a "no info in `glance` that you could get from the model call" policy, so `REML` and `measure` violate that. I can see an argument for keeping them though. As for adding the *IC / logLik stuff, do people actually use that for meta analysis models?? If we do add it in, let's add it to the right (although still keeping `nobs` at the far right).

**Comment by malcolmbarrett** [comment] 2019-04-11 04:02
I will move `nobs` as well. I don't think `measure` and `method` are that interesting, either. Re: useful stats, people usually use the other ones but some do use the ones that are missing because of that bug

**Comment by malcolmbarrett** [comment] 2019-04-16 21:47
Quick update on the z-statistic: this is already present in the `statistic` column. That's consistent with other tidiers, yeah? I was surprised when I thought I missed adding that!

**Comment by wviechtb** [comment] 2019-04-18 16:33
Hi all! It's great that methods for `rma` objects have been added to `broom`. I actually wrote `glance.rma()` and `tidy.rma()` methods myself a while ago, because that allowed the [mice](https://cran.r-project.org/package=mice) package to play nicely together with `metafor`. Now that official `glance.rma()` and `tidy.rma()` methods that have been added to `broom`, this no longer works.

For `mice` to work together with `metafor`, `glance.rma()` needs to include variable `df.residual`, which you can easily get from `df.residual(x)`, so I hope this can be added (i.e., add `df.residual=df.residual(x)` to the list inside `glance.rma()`). However, the way `tidy.rma()` works breaks the compatibility, because `mice` expects a `term` variable and it also doesn't expect the results from individual studies to be included (only the model coefficients). So, would it be okay to change the default to `include_studies = FALSE` and change `study` to `term`? The `type` variable still clarifies what is a `study` and what is a model coefficient (`summary`), so it is still clear what is being returned.

**Comment by malcolmbarrett** [comment] 2019-04-18 16:50
Ahh, that's a pretty good reason to make those changes. I'll add it to #694 if it makes sense to @alexpghayes

**Comment by alexpghayes** [comment] 2019-04-18 17:31
I'm largely on board with this, but would like to think about this a little more. Can you point to me to portion of `mice` that makes use of `broom`? Is the idea that `tidy()` and `glance()` allow `mice` to have a single function to impute many models instead of a generic? If so I want to think about when and why that might break.

**Comment by alexpghayes** [comment] 2019-04-18 17:37
@wviechtb Can I ask where your `tidy.rma()` and `glance.rma()` lived? Where they in `metafor` itself, or somewhere else?

**Comment by wviechtb** [comment] 2019-04-18 18:26
See `help(pool, package="mice")`. In particular:

    The function requires the following input from each fitted model:
    
      1. the estimates of the model, usually obtainable by coef()
      2. the standard error of each estimate;
      3. the residual degrees of freedom of the model.
    
    The pool() function relies on the broom::tidy and broom::glance function for extracting this information from a list of fitted models.

The methods I wrote were just quick hacks to get `mice` to play with `metafor`. In essence:

```
glance.rma <- function (x, ...) {
   data.frame(R2 = x$R2, tau2=x$tau2, logLik=logLik(x), AIC=AIC(x), BIC=BIC(x), deviance=deviance(x), df.residual=df.residual(x))
}

tidy.rma <- function (x, ...) {
   ret <- coef(summary(x))
   colnames(ret)[2] <- "std.error"
   ret$term <- rownames(ret)
   return(ret)
}
```

They weren't tibbles and I did not put them in `metafor` or anywhere else. I was considering adding them to `metafor` at some point but it makes much more sense to have proper methods directly in `broom`, assuming that they do play nicely together with `mice`.

**Comment by alexpghayes** [comment] 2019-08-07 15:17
@malcolmbarrett Do the current tidiers (now that I've merged the bugfix) play well with `mice`? Are there additional changes we should consider?

**Comment by malcolmbarrett** [comment] 2019-08-09 15:16
I don't think that will have fixed all the issues, as I didn't incorporate @wviechtb's changes. I believe we just need to change the default for `tidy.rma()` to `include_studies = FALSE` and add `df.residual = df.residual(x)` to `glance.rma()` to make that happen, right @wviechtb? I don't have time this week, but maybe @softloud does. If not, I can do it next week

**Comment by alexpghayes** [comment] 2019-08-09 15:23
@wviechtb I don't use `mice` at all. Can you provide an example use based on your helpers that we can turn into a test for the tidying methods?

**Comment by malcolmbarrett** [comment] 2019-09-24 14:59
@wviechtb if you're able to provide us what @alexpghayes suggests, I think I can work on this soon. Thanks!

**Comment by wviechtb** [comment] 2019-10-09 14:46
Sorry for the slow reply. Thanks for trying to make this work! Unfortunatly, what you are currently doing doesn't. First of all, there is a bit of an inconsistency as to what `tidy()` does for `rma` objects versus other regression-type objects. An example:

    devtools::install_github("tidymodels/broom")
    library(broom)
    library(metafor)

    # create a toy dataset
    dat <- data.frame(yi = c(.1, .2, .3, .4, .5), 
                      vi = c(.01, .02, .04, .02, .01), 
                      xi = c(0, 2, 1, NA, 5))

    # fit a model with lm()
    res <- lm(yi ~ xi, data=dat)
    tidy(res)

    # now fit a proper meta-regression model with rma()
    res <- rma(yi, vi, mods = ~ xi, data=dat)
    tidy(res)

That's not (IMHO) what `tidy()` should provide here. Like for `lm` objects, it should not include the 'raw' data (i.e., the study values). Also, it needs to include a `term` variable.

At the core, it should be:

    tidy.rma <- function (x, ...) {
        ret <- coef(summary(x))
        colnames(ret)[2] <- "std.error"
        ret$term <- rownames(ret)
        return(ret)
    }

    tidy(res)

Also, for the `mice` package to play nicely together with `metafor`, the `glance()` method should include `df.residual`, which you can easily get from an `rma` object with `df.residual()`. The following would be sufficient, but of course you can add other things:

    glance.rma <- function (x, ...)
       data.frame(df.residual=df.residual(x))

    glance(res)

So, at the moment, `mice` and `metafor` won't be able to interact:

    library(mice)

    imp <- mice(dat, print=FALSE, seed=1234)

    fit <- with(imp, rma(yi, vi, mods = ~ xi))
    pool <- pool(fit)

So, `tidy()` can't find `term` (plus with the study results included in the output, this isn't likely to work anyway) and `glance()` can't get `df.residual`. Now let's replace the `broom:tidy.rma` and `broom::glance.rma` functions with the ones I created above:

    assignInNamespace("tidy.rma",   tidy.rma,   ns="broom")
    assignInNamespace("glance.rma", glance.rma, ns="broom")

And now things work as intended:

    pool <- pool(fit)
    round(summary(pool), 4)

If you want to have `tidy()` also provide the individual study results, then you could make that an argument that by default is `FALSE`. Or you could consider a separate `tidy()` method for `escalc` objects:

    dat <- escalc(measure="RR", ai=tpos, bi=tneg, ci=cpos, di=cneg, data=dat.bcg)
    dat
    tidy(dat) # no such method at the moment

Actually, the `metafor::summary.escalc` method already does something similar:

    summary(dat)

That might be something for down the road, but for now, I think the more important part would be to change `broom:tidy.rma` and `broom::glance.rma` methods.

**Comment by malcolmbarrett** [comment] 2019-10-09 14:49
Thanks @wviechtb! These are pretty easy changes, and I agree they are worth making. Assuming @alexpghayes is on board, I can get a patch in soon

**Comment by wviechtb** [comment] 2019-10-09 14:54
I actually now see that @malcolmbarrett made essentially the same suggestion (and I did not see the `include_studies` argument). So, make that `FALSE` by default, add `term`, add `df.residual=df.residual(x)` to `glance.rma()` and that should do it. At least now you have a toy dataset to check that it works.

**Comment by alexpghayes** [comment] 2019-10-09 15:56
I'm on board!

**Closed** 2019-10-12 21:21 UTC

**Comment by malcolmbarrett** [comment] 2019-10-12 21:23
Awesome. Thanks, everyone!
