### ISSUE TITLE
tidy() cannot convert pwr.2p2n object properly

### ISSUE THREAD

**Issue by RobBinS83** [tidymodels/broom#1054] opened 2021-09-30 15:35 UTC
Hi there,

I have tried to convert objects generated by pwr.2p and pwr.2p2n functions to data.frames. The result is fine with pwr.2p but not for pwr.2p2n (n1, n2 columns are missing). 

```
library(broom)
library(pwr)

power_test = pwr.2p2n.test(h = ES.h(p1=0.06, p2=0.05), n1 = 200000, n2=NULL, sig.level=0.05, power=0.9, alternative="greater")
print(power_test)
df = data.frame(broom::tidy(power_test))
print(df)
```

Anyone can help with this?

Regards,
Jing

**Comment by simonpcouch** [comment] 2021-09-30 19:54
Thanks for the issue!

Can you please provide a minimal [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example), using the `reprex` package? A reprex will help me troubleshoot and fix your issue more quickly.🙂

**Comment by RobBinS83** [comment] 2021-09-30 21:06
Hi, I just edited the codes above, so it can run successfully. Unfortunately, I don't know how to use `reprex` package.

**Comment by simonpcouch** [comment] 2021-10-04 00:53
Ah, I see. So, the `tidy.power.htest` function was written for objects outputted from the base `stats` package. It looks like the `pwr` package exports a function which supplies an object of the same class `power.htest`, but doesn't actually behave like an `power.htest` object as supplied by base R. Introducing support here is outside of the scope of the package at this point in its lifecycle, so I'll go ahead close this issue—thanks for the issue and for updating your code.

**Closed by simonpcouch** 2021-10-04 00:53 UTC
